### ISSUE TITLE
 Redirect links

### ISSUE THREAD

**Issue by don-vip** [OsmHackTW/josm-presets#5]
https://github.com/OsmHackTW/josm-presets/blob/master/TaiwanOnly.xml has redirect links, can you please fix them?

Found HTTP redirection for http://wiki.openstreetmap.org/wiki/Tag:natural=tree -> 301 -> https://wiki.openstreetmap.org/wiki/Tag:natural=tree
Found HTTP redirection for https://osmtw.hackpad.com/OSM-lis34MoHRDu -> 301 -> https://paper.dropbox.com/hackpad/
Found HTTP redirection for http://beta.hackfoldr.org/drinking-water/-OSM-tag--nPGPthGklwG -> 301 -> https://beta.hackfoldr.org/drinking-water/-OSM-tag--nPGPthGklwG
Found HTTP redirection for http://www.post.gov.tw/post/internet/Postal/index.jsp?ID=208 -> 302 -> https://www.post.gov.tw/post/internet/Postal/index.jsp?ID=208

See https://josm.openstreetmap.de/ticket/17240

**Comment by Klumbumbus** [comment]
@don-vip the test still fails at https://beta.hackfoldr.org/drinking-water/-OSM-tag--nPGPthGklwG but I think this URL is OK!?

**Comment by yellowsoar** [comment]
> @don-vip the test still fails at https://beta.hackfoldr.org/drinking-water/-OSM-tag--nPGPthGklwG but I think this URL is OK!?

Since hackfoldr was designed to organize hackpads.
https://beta.hackfoldr.org/drinking-water/-OSM-tag--nPGPthGklwG 
Link above will try to get :
https://osmtw.hackpad.com/-OSM-tag--nPGPthGklwG
Which is not available now and will be redirect to drinking-water hackfoldr home page here:
https://beta.hackfoldr.org/drinking-water/
But, as osmtw.hackpad.com already been migrated to osmtw.hackpad.tw
The link is now in new domain with same path below:
https://osmtw.hackpad.tw/-OSM-tag--nPGPthGklwG
So, I think change the link will solve the redirect problem:
https://beta.hackfoldr.org/drinking-water/https%253A%252F%252Fosmtw.hackpad.tw%252F-OSM-tag--nPGPthGklwG

**Comment by don-vip** [comment]
I've ignored the remaining errors on JOSM wiki
